#!/bin/bash

sudo true
git clone https://aur.archlinux.org/yay.git && cd yay/ && makepkg -si --noconfirm && cd .. && rm -rf yay/
yay -Sy --needed $(cat base pkg | egrep -v "^\s*(#|$)")

#Xdman
wget --no-check-certificate https://github.com/hmanhng/xdm/raw/main/xdm.sh && sudo sh ./xdm.sh && rm -f xdm.sh

git config --global user.email "hmanhng@icloud.com"
git config --global user.name "hmanhng"

sudo sed -i 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf
sudo sed -i 's/Logo=1/Logo=0/g' /etc/libreoffice/sofficerc

cp -rf dotfiles/. $HOME/
sudo cp -rf $HOME/etc/* /etc && rm -rf $HOME/etc
sudo cp -rf $HOME/usr/* /usr && rm -rf $HOME/usr

# Fonts
git clone https://github.com/hmanhng/WindowsFonts.git $HOME/WindowsFonts && rm -rf $HOME/WindowsFonts/.git && sudo mv $HOME/WindowsFonts/ /usr/share/fonts/ && sudo chmod 644 /usr/share/fonts/WindowsFonts/*
git clone https://github.com/hmanhng/fonts.git $HOME/.local/share/fonts && rm -rf $HOME/.local/share/fonts/.git
fc-cache --force

#GDM
sudo cp $HOME/Pictures/icon.jpg /var/lib/AccountsService/icons/
cp $HOME/Pictures/icon.jpg $HOME/.face
sudo bash -c 'cat dotfiles/bisu > /var/lib/AccountsService/users/bisu' && rm $HOME/bisu

sudo systemctl enable bluetooth
sudo systemctl enable gdm
sudo systemctl enable touchegg
sudo systemctl enable systemd-timesyncd

sudo bash -c 'echo 259:2 > /sys/power/resume'
sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg

# gnome settings
dconf load / < settings.dconf

# install neovim
curl -fsSL https://fnm.vercel.app/install | bash
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y
fnm install 16.15.0
npm i -g bash-language-server
dotnet tool install --global csharp-ls
