#!/bin/bash

sudo true
git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si --noconfirm && cd .. && rm -rf yay-bin
yay -Sy --needed --batchinstall --removemake --nodiffmenu --noconfirm $(cat base pkg | egrep -v "^\s*(#|$)")

flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install --user \
org.videolan.VLC \
com.obsproject.Studio \
com.discordapp.Discord \
org.qbittorrent.qBittorrent \
com.spotify.Client \
nl.hjdskes.gcolor3 \
org.libreoffice.LibreOffice \
org.gnome.FileRoller \
org.gnome.eog \
org.gnome.Evince \
org.xfce.mousepad

#Xdman
wget --no-check-certificate https://github.com/hmanhng/xdm/raw/main/xdm.sh && sudo sh ./xdm.sh && rm -f xdm.sh

echo "Install fnm" && read a
curl -fsSL https://fnm.vercel.app/install | bash
~/.fnm/fnm install 16.15.0
echo "Install done" && read a

git config --global user.email "hmanhng@icloud.com"
git config --global user.name "hmanhng"

sudo sed -i 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf

cp -rf dotfiles/. $HOME/
sudo cp -rf $HOME/etc/* /etc && rm -rf $HOME/etc
sudo cp -rf $HOME/usr/* /usr && rm -rf $HOME/usr

# Fonts
git clone https://github.com/hmanhng/WindowsFonts.git $HOME/WindowsFonts && rm -rf $HOME/WindowsFonts/.git && sudo mv $HOME/WindowsFonts/ /usr/share/fonts/ && sudo chmod 644 /usr/share/fonts/WindowsFonts/*
git clone https://github.com/hmanhng/fonts.git $HOME/.local/share/fonts && rm -rf $HOME/.local/share/fonts/.git
fc-cache --force

#GDM
sudo cp $HOME/Pictures/icon.jpg /var/lib/AccountsService/icons/
cp $HOME/Pictures/icon.jpg $HOME/.face
sudo bash -c 'cat dotfiles/bisu > /var/lib/AccountsService/users/bisu' && rm $HOME/bisu

sudo systemctl enable systemd-timesyncd
sudo systemctl enable bluetooth
sudo systemctl enable gdm
sudo systemctl enable touchegg

echo "ideapad_laptop" | sudo tee -a /etc/modules
echo "$USERNAME ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode" | sudo tee -a /etc/sudoers.d/$USERNAME
sudo bash -c 'echo 259:2 > /sys/power/resume'
sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg

# gnome settings
dconf load / < settings.dconf

# lunarvim
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y
npm i -g bash-language-server
dotnet tool install --global csharp-ls

# dotfiles
git clone https://github.com/hmanhng/dotfile.git ~/dotfiles && cd ~/dotfiles && ./install.sh

# Zsh
sudo chsh $USER -s "/bin/zsh"
